### ISSUE TITLE
Unsupported props are being passed to DOM elements

### ISSUE THREAD

**Issue by jaredkirkley** [DCCS-IT-Business-Solutions/react-searchable-select-mui#2] opened 2019-10-21 14:15 UTC
I got the select working perfectly!  Thanks for this!

I do, however keep getting a few warnings regarding some of the props being passed to DOM elements:

this one referring to the ClickAwayListener:
`Failed prop type: The following props are not supported: 'aria-selected', 'onClick', 'role', 'selected', 'value', 'data-value'. Please remove them.`

these 2 referring to a div in ForwardRef(InputBase):
`React does not recognize the 'keyPropFn' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'keypropfn' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

`React does not recognize the 'valuePropFn' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'valuepropfn' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

When I lowercase the props as suggested, the component no longer works and React still complains about the lowercase props being on a DOM element.

Any help would be greatly appreciated!

I think it may be related to passing `{...others}` as props to the Select on line 93 of SearchableSelect.tsx

edit: I suppose I should mention that I'm using react and react-dom v16.10.2

edit: Can confirm that if you `delete others.keyPropFn` and `delete others.valuePropFn`, the second 2 errors disappear.  Still working on seeing if I can get rid of the 1st error.

edit: the 1st error is a bit tougher as anything inside a Select mui component automatically gets those props added to them, so the ClickAwayListener is getting them as a side effect.

**Comment by mvitzthum** [comment] 2019-10-23 09:02
Hey @jaredkirkley 
Can you try to recreate the error on the clickawaylistener with https://codesandbox.io or another online editor of your choice? 

Thanks for the detailed explanation for the other 2 errors, gonna fix them :)

**Comment by mvitzthum** [comment] 2019-10-23 09:08
Nevermind, already recreated them myself :)

**Comment by mvitzthum** [comment] 2019-10-23 14:45
@jaredkirkley 
keyPropFn and valuePropFn are fixed in Version 0.2.6

The error on the ClickAwayListener seems to be gone aswell.... weird.
Or i can't reproduce it anymore.
https://dccs-it-business-solutions.github.io/react-searchable-select-mui/?path=/story/searchable-select--examples
-> Errors in console are gone for me in the storybook

**Comment by jaredkirkley** [comment] 2019-10-23 15:01
Is that maybe using a previous version of Material-ui?  I'm using ^4.5.0

**Comment by mvitzthum** [comment] 2019-10-24 11:22
I was able to reproduce it again.

I found a solution for the last error.

Since i can't stop MUI-Select from passing down onclick, role, etc. I wrapped the ClickAwayListener in a Component that ignores these props.

There was an additional "ref"-Error, so i used a React.Component instead of a functional component.

Should be fixed in Version 0.2.7 :)

**Comment by mvitzthum** [comment] 2019-10-24 11:24
![image](https://user-images.githubusercontent.com/47003029/67481085-9d21a800-f661-11e9-99f7-8cc08db8a8bd.png)

**Comment by jaredkirkley** [comment] 2019-10-24 13:16
@mvitzthum You are amazing!

Thank you so much for your quick replies and dedication to your package!

I am very much looking forward to 0.2.7

It's definitely unfortunate that MUI doesn't seem to think a filterable dropdown should be standard in their library when it's a part of so many others.  Thank you and your team for developing this and making it available to the community.  You and the package have been an immense help to me!

Keep up the great work!

**Closed** 2019-10-24 13:24 UTC

**Comment by mvitzthum** [comment] 2019-10-24 13:32
@mvitzthum 
Hey, 
thank you for the kind words. 
The only reason i knew what to do, was because of your detailed explanations :P

Also!
I added showAll/maxVisibleOptions since MenuItems are extremly slow while rendering.

Default is now 20 options.
In Version 0.2.9
